# Métodos Predictivos: Introducción a Python

<img src="https://economiapce.files.wordpress.com/2022/05/universidadsergioarboleda.jpg?w=1140&h=741" width="200" height="auto" alt="Logo de la Universidad">


Bienvenidos a la clase de Introducción a Python enfocada en Métodos Predictivos. En esta sesión, exploraremos los fundamentos de Python y cómo aplicarlos en el análisis predictivo de datos.


## Paython 101 - Funciones, Estrucutras de Datos

### Funciones

In [ ]:
print("Hola mundo")

Hola mundo


In [ ]:
2+2

4

In [ ]:
def add_numbers(x, y):
    return x + y

add_numbers(1, 2)

3

In [ ]:
variable = True
if variable:
  print("HOLA")
else:
  print("BUENOS DIAS")

HOLA


In [ ]:
i=0
while i<10:
  print(i*"*")
  i=i+1


*
**
***
****
*****
******
*******
********
*********


In [ ]:
for i in range(0,10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
def add_numbers(x,y,z=None):
    if (z==None):
        return x+y
    else:
        return x+y+z

print(add_numbers(1,5))
print(add_numbers(1, 5, 3))

6
9


In [ ]:
def add_numbers(x, y, z=None, flag=False):
    if (z==None):
      if flag:
        print('Flag is true!')
        return x + y
    else:
      if flag:
        print('Buenos dias!')
        return x + y +z
      else:
        print("Buenas Noches")

print(add_numbers(1, 2, flag=False))

None


In [ ]:
nombre = "Javier"
print(type(nombre))

<class 'str'>


In [ ]:
names = ["Javier","Maria",False,0]
for name in names :
  print(name)

Javier
Maria
False
0


In [ ]:
name = "Javier"
apellido = "Herrera"
print(name +" " +apellido)

Javier Herrera


In [ ]:
variable = 0
while variable<3:
  variable = variable +1
  print("hola")

hola
hola
hola


In [ ]:
for i:
  for j in range(0,10):
    print(juan*j)


Javier
JavierJavier
JavierJavierJavier
JavierJavierJavierJavier
JavierJavierJavierJavierJavier
JavierJavierJavierJavierJavierJavier
JavierJavierJavierJavierJavierJavierJavier
JavierJavierJavierJavierJavierJavierJavierJavier
JavierJavierJavierJavierJavierJavierJavierJavierJavier

Maria
MariaMaria
MariaMariaMaria
MariaMariaMariaMaria
MariaMariaMariaMariaMaria
MariaMariaMariaMariaMariaMaria
MariaMariaMariaMariaMariaMariaMaria
MariaMariaMariaMariaMariaMariaMariaMaria
MariaMariaMariaMariaMariaMariaMariaMariaMaria
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0
0


### Estrucutras de Datos

In [3]:
type(23.0)

float

In [ ]:
type(list())

list

In [ ]:
type(None)

NoneType

In [ ]:
type(1)

int

In [ ]:
type(1.0)

float

In [4]:
x = (1, 'a', 2, 'b')
type(x)

tuple

### Listas

In [7]:
variable = 1
variable2 = 2

In [10]:
x = [1, 'a', 2, 'b',variable2,variable]
print(x)

[1, 'a', 2, 'b', 2, 1]


In [11]:
x.append(3.3)
print(x)

[1, 'a', 2, 'b', 2, 1, 3.3]


In [12]:
for item in x:
  print(item)

1
a
2
b
2
1
3.3


In [13]:
len(x)

7

In [ ]:
i=0
while( i != len(x) ):
    print(x[i])
    i = i + 1

1
a
2
b
3.3
3.3
3.3
3.3
3.3
3.3
3.3


In [14]:
[1,2] + [3,4]

[1, 2, 3, 4]

In [15]:
[1]*3

[1, 1, 1]

In [18]:
1 in [1, 2, 3]

True

In [19]:
x = 'Esto es un string pero tambien es una lista'
print(x[0])
print(x[0:5])
print(x[0:10])

E
Esto 
Esto es un


In [20]:
x.split(" ")

['Esto', 'es', 'un', 'string', 'pero', 'tambien', 'es', 'una', 'lista']

In [ ]:
x[-1]

'a'

In [21]:
x[-10:-5]

' una '

In [22]:
x[:3]

'Est'

In [23]:
x[3:]

'o es un string pero tambien es una lista'

In [25]:
nombre = 'Julio Mario'
apellido = 'Santodomingo'

print(nombre + ' ' + apellido)
print(nombre *3)
print('Julio' in nombre)


Julio Mario Santodomingo
Julio MarioJulio MarioJulio Mario
True


In [26]:
primer_nombre = 'Julio Mario Santo Domingo Pumarejo'.split(' ')[0]
primer_apellido = 'Julio Mario Santo Domingo Pumarejo'.split(' ')[-2]
print(primer_nombre)
print(primer_apellido)

Julio
Domingo


In [ ]:
'Julio Mario Santo Domingo Pumarejo'.split(' ')

['Julio', 'Mario', 'Santo', 'Domingo', 'Pumarejo']

**Importante:** Hay que tener en cuenta que cada tipo de datos tiene sus propiedades."split" es un atributo de un objeto tipo string

In [27]:
'Chris' + 2

TypeError: can only concatenate str (not "int") to str

In [28]:
'Chris' + " " +str(2)

'Chris 2'

### Diccionarios: Tal vez el recurso más util en programación en Python

In [ ]:
x = {'Christopher Brooks': 'brooksch@umich.edu',
     'Bill Gates': 'billg@microsoft.com'}
x['Christopher Brooks'] # Retrieve a value by using the indexing operator


'brooksch@umich.edu'

In [ ]:
x['Kevyn Collins-Thompson'] = None
x['Kevyn Collins-Thompson']

In [ ]:
x

{'Christopher Brooks': 'brooksch@umich.edu',
 'Bill Gates': 'billg@microsoft.com',
 'Kevyn Collins-Thompson': None}

In [ ]:
for name in x:
   print(x[name])

brooksch@umich.edu
billg@microsoft.com
None


In [ ]:
for email in x.values():
    print(email)

brooksch@umich.edu
billg@microsoft.com
None


In [ ]:
for name, email in x.items():
    print(name)
    print(email)

Christopher Brooks
brooksch@umich.edu
Bill Gates
billg@microsoft.com
Kevyn Collins-Thompson
None


In [ ]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu')
fname, lname, email = x

In [ ]:
x = ('Christopher', 'Brooks', 'brooksch@umich.edu', 'Ann Arbor')
fname, lname, email, _ = x

### Algo de Python Avanzado: Listas de Comprensión (List Comprehension)

In [ ]:
# Método tradicional
lista = []
for letra in 'casa':
    lista.append(letra)
print(lista)

['c', 'a', 's', 'a']


In [ ]:
# Con comprensión de listas
lista = [letra for letra in 'casa']
print(lista)

['c', 'a', 's', 'a']


In [ ]:
%time
# Método tradicional
lista = []
for numero in range(0,1000):
    lista.append(numero**2)
print(lista)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 6.91 µs
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000, 10201, 10404, 10609, 10816, 11025, 11236, 11449, 11664, 11881, 12100, 12321, 12544, 12769, 12996, 13225, 13456, 13689, 13924, 14161, 14400, 14641, 14884, 15129, 15376, 15625, 15876, 16129, 16384, 16641, 16900, 17161, 17424, 17689, 17956, 18225, 18496, 18769, 19044, 19321, 19600, 19881, 20164, 20449, 20736, 21025, 21316, 21609, 21904, 22201, 22500, 22801, 23104, 23409, 237

In [ ]:
%time
# Con comprensión de listas
lista = [numero**2 for numero in  range(0,1000)]
print(lista)

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 7.63 µs
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000, 10201, 10404, 10609, 10816, 11025, 11236, 11449, 11664, 11881, 12100, 12321, 12544, 12769, 12996, 13225, 13456, 13689, 13924, 14161, 14400, 14641, 14884, 15129, 15376, 15625, 15876, 16129, 16384, 16641, 16900, 17161, 17424, 17689, 17956, 18225, 18496, 18769, 19044, 19321, 19600, 19881, 20164, 20449, 20736, 21025, 21316, 21609, 21904, 22201, 22500, 22801, 23104, 23409, 237

Strings

In [ ]:
sales_record = {
'price': 3.24,
'num_items': 4,
'person': 'Chris'}

sales_statement = '{} bought {} item(s) at a price of {} each for a total of {}'

print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))


Chris bought 4 item(s) at a price of 3.24 each for a total of 12.96


## Manejo de Datos en Python

In [29]:
!wget https://raw.githubusercontent.com/rashida048/Datasets/master/home_data.csv

--2024-02-22 21:32:00--  https://raw.githubusercontent.com/rashida048/Datasets/master/home_data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2598020 (2.5M) [text/plain]
Saving to: ‘home_data.csv’

home_data.csv       100%[===================>]   2.48M  --.-KB/s    in 0.05s   

2024-02-22 21:32:00 (51.9 MB/s) - ‘home_data.csv’ saved [2598020/2598020]



In [30]:
import csv

%precision 2

with open('home_data.csv') as csvfile:
    mpg = list(csv.DictReader(csvfile))

mpg[:3] # The first three dictionaries in our list.

[{'id': '7129300520',
  'date': '20141013T000000',
  'price': '221900',
  'bedrooms': '3',
  'bathrooms': '1',
  'sqft_living': '1180',
  'sqft_lot': '5650',
  'floors': '1',
  'waterfront': '0',
  'view': '0',
  'condition': '3',
  'grade': '7',
  'sqft_above': '1180',
  'sqft_basement': '0',
  'yr_built': '1955',
  'yr_renovated': '0',
  'zipcode': '98178',
  'lat': '47.5112',
  'long': '-122.257',
  'sqft_living15': '1340',
  'sqft_lot15': '5650'},
 {'id': '6414100192',
  'date': '20141209T000000',
  'price': '538000',
  'bedrooms': '3',
  'bathrooms': '2.25',
  'sqft_living': '2570',
  'sqft_lot': '7242',
  'floors': '2',
  'waterfront': '0',
  'view': '0',
  'condition': '3',
  'grade': '7',
  'sqft_above': '2170',
  'sqft_basement': '400',
  'yr_built': '1951',
  'yr_renovated': '1991',
  'zipcode': '98125',
  'lat': '47.721',
  'long': '-122.319',
  'sqft_living15': '1690',
  'sqft_lot15': '7639'},
 {'id': '5631500400',
  'date': '20150225T000000',
  'price': '180000',
  'bedroo

In [ ]:
len(mpg)

21613

In [ ]:
mpg[0].keys()

dict_keys(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long', 'sqft_living15', 'sqft_lot15'])

### Librerias
![Image](https://nullclass.com/wp-content/uploads/2022/02/top-python-libraries-a-data-scientist-need-to-know.jpg)

In [32]:
import pandas as pd
data = pd.read_csv("home_data.csv")
data.head(10)

id             date    price  bedrooms  bathrooms  sqft_living  \
0  7129300520  20141013T000000   221900         3       1.00         1180   
1  6414100192  20141209T000000   538000         3       2.25         2570   
2  5631500400  20150225T000000   180000         2       1.00          770   
3  2487200875  20141209T000000   604000         4       3.00         1960   
4  1954400510  20150218T000000   510000         3       2.00         1680   
5  7237550310  20140512T000000  1225000         4       4.50         5420   
6  1321400060  20140627T000000   257500         3       2.25         1715   
7  2008000270  20150115T000000   291850         3       1.50         1060   
8  2414600126  20150415T000000   229500         3       1.00         1780   
9  3793500160  20150312T000000   323000         3       2.50         1890   

   sqft_lot  floors  waterfront  view  ...  grade  sqft_above  sqft_basement  \
0      5650     1.0           0     0  ...      7        1180              0   
1      7242     2.0           0     0  ...      7        2170            400   
2     10000     1.0           0     0  ...      6         770              0   
3      5000     1.0           0     0  ...      7        1050            910   
4      8080     1.0           0     0  ...      8        1680              0   
5    101930     1.0           0     0  ...     11        3890           1530   
6      6819     2.0           0     0  ...      7        1715              0   
7      9711     1.0           0     0  ...      7        1060              0   
8      7470     1.0           0     0  ...      7        1050            730   
9      6560     2.0           0     0  ...      7        1890              0   

   yr_built  yr_renovated  zipcode      lat     long  sqft_living15  \
0      1955             0    98178  47.5112 -122.257           1340   
1      1951          1991    98125  47.7210 -122.319           1690   
2      1933             0    98028  47.7379 -122.233           2720   
3      1965             0    98136  47.5208 -122.393           1360   
4      1987             0    98074  47.6168 -122.045           1800   
5      2001             0    98053  47.6561 -122.005           4760   
6      1995             0    98003  47.3097 -122.327           2238   
7      1963             0    98198  47.4095 -122.315           1650   
8      1960             0    98146  47.5123 -122.337           1780   
9      2003             0    98038  47.3684 -122.031           2390   

   sqft_lot15  
0        5650  
1        7639  
2        8062  
3        5000  
4        7503  
5      101930  
6        6819  
7        9711  
8        8113  
9        7570  

[10 rows x 21 columns]

In [33]:
data.shape

(21613, 21)

In [34]:
data.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [35]:
data["id"]

0        7129300520
1        6414100192
2        5631500400
3        2487200875
4        1954400510
            ...    
21608     263000018
21609    6600060120
21610    1523300141
21611     291310100
21612    1523300157
Name: id, Length: 21613, dtype: int64

In [36]:
data.id

0        7129300520
1        6414100192
2        5631500400
3        2487200875
4        1954400510
            ...    
21608     263000018
21609    6600060120
21610    1523300141
21611     291310100
21612    1523300157
Name: id, Length: 21613, dtype: int64

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21613 entries, 0 to 21612
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             21613 non-null  int64  
 1   date           21613 non-null  object 
 2   price          21613 non-null  int64  
 3   bedrooms       21613 non-null  int64  
 4   bathrooms      21613 non-null  float64
 5   sqft_living    21613 non-null  int64  
 6   sqft_lot       21613 non-null  int64  
 7   floors         21613 non-null  float64
 8   waterfront     21613 non-null  int64  
 9   view           21613 non-null  int64  
 10  condition      21613 non-null  int64  
 11  grade          21613 non-null  int64  
 12  sqft_above     21613 non-null  int64  
 13  sqft_basement  21613 non-null  int64  
 14  yr_built       21613 non-null  int64  
 15  yr_renovated   21613 non-null  int64  
 16  zipcode        21613 non-null  int64  
 17  lat            21613 non-null  float64
 18  long  

In [39]:
data.describe()

id         price      bedrooms     bathrooms   sqft_living  \
count  2.161300e+04  2.161300e+04  21613.000000  21613.000000  21613.000000   
mean   4.580302e+09  5.400881e+05      3.370842      2.114757   2079.899736   
std    2.876566e+09  3.671272e+05      0.930062      0.770163    918.440897   
min    1.000102e+06  7.500000e+04      0.000000      0.000000    290.000000   
25%    2.123049e+09  3.219500e+05      3.000000      1.750000   1427.000000   
50%    3.904930e+09  4.500000e+05      3.000000      2.250000   1910.000000   
75%    7.308900e+09  6.450000e+05      4.000000      2.500000   2550.000000   
max    9.900000e+09  7.700000e+06     33.000000      8.000000  13540.000000   

           sqft_lot        floors    waterfront          view     condition  \
count  2.161300e+04  21613.000000  21613.000000  21613.000000  21613.000000   
mean   1.510697e+04      1.494309      0.007542      0.234303      3.409430   
std    4.142051e+04      0.539989      0.086517      0.766318      0.650743   
min    5.200000e+02      1.000000      0.000000      0.000000      1.000000   
25%    5.040000e+03      1.000000      0.000000      0.000000      3.000000   
50%    7.618000e+03      1.500000      0.000000      0.000000      3.000000   
75%    1.068800e+04      2.000000      0.000000      0.000000      4.000000   
max    1.651359e+06      3.500000      1.000000      4.000000      5.000000   

              grade    sqft_above  sqft_basement      yr_built  yr_renovated  \
count  21613.000000  21613.000000   21613.000000  21613.000000  21613.000000   
mean       7.656873   1788.390691     291.509045   1971.005136     84.402258   
std        1.175459    828.090978     442.575043     29.373411    401.679240   
min        1.000000    290.000000       0.000000   1900.000000      0.000000   
25%        7.000000   1190.000000       0.000000   1951.000000      0.000000   
50%        7.000000   1560.000000       0.000000   1975.000000      0.000000   
75%        8.000000   2210.000000     560.000000   1997.000000      0.000000   
max       13.000000   9410.000000    4820.000000   2015.000000   2015.000000   

            zipcode           lat          long  sqft_living15     sqft_lot15  
count  21613.000000  21613.000000  21613.000000   21613.000000   21613.000000  
mean   98077.939805     47.560053   -122.213896    1986.552492   12768.455652  
std       53.505026      0.138564      0.140828     685.391304   27304.179631  
min    98001.000000     47.155900   -122.519000     399.000000     651.000000  
25%    98033.000000     47.471000   -122.328000    1490.000000    5100.000000  
50%    98065.000000     47.571800   -122.230000    1840.000000    7620.000000  
75%    98118.000000     47.678000   -122.125000    2360.000000   10083.000000  
max    98199.000000     47.777600   -121.315000    6210.000000  871200.000000

### Dates and Times

In [40]:
type(data["date"][0])

str

In [ ]:
import datetime as dt
# Suponiendo que df es tu DataFrame y 'fecha' es el nombre de tu columna
data['date'] = pd.to_datetime(data['date'], format='%Y%m%dT%H%M%S')
data["date"]

0       2014-10-13
1       2014-12-09
2       2015-02-25
3       2014-12-09
4       2015-02-18
           ...    
21608   2014-05-21
21609   2015-02-23
21610   2014-06-23
21611   2015-01-16
21612   2014-10-15
Name: date, Length: 21613, dtype: datetime64[ns]

In [ ]:
data["date"].value_counts()

2014-06-23    142
2014-06-26    131
2014-06-25    131
2014-07-08    127
2015-04-27    126
             ... 
2014-11-02      1
2015-01-31      1
2015-05-24      1
2014-05-17      1
2014-07-27      1
Name: date, Length: 372, dtype: int64

In [ ]:
# import pandas as pd
# import datetime as dt

# # Supongamos que df es tu DataFrame y 'fecha' es el nombre de tu columna
# data['date'] = data['date'].apply(lambda x: dt.datetime.strptime(x, '%Y%m%dT%H%M%S'))
# data['date']

In [42]:
data["price"].describe()

count    2.161300e+04
mean     5.400881e+05
std      3.671272e+05
min      7.500000e+04
25%      3.219500e+05
50%      4.500000e+05
75%      6.450000e+05
max      7.700000e+06
Name: price, dtype: float64

In [47]:
data["price"].mean()

540088.1419053348

In [44]:
data["price"].max()

7700000

In [45]:
data["bedrooms"].value_counts()

3     9824
4     6882
2     2760
5     1601
6      272
1      199
7       38
0       13
8       13
9        6
10       3
11       1
33       1
Name: bedrooms, dtype: int64

In [ ]:
data.groupby(["bedrooms"]).agg({"price":["mean","max","min"]})

price                 
                  mean      max     min
bedrooms                               
0         4.095037e+05  1295648  139950
1         3.176429e+05  1247000   75000
2         4.013727e+05  3278000   78000
3         4.662321e+05  3800000   82000
4         6.354195e+05  4489000  100000
5         7.865998e+05  7062500  133000
6         8.255206e+05  7700000  175000
7         9.511847e+05  3200000  280000
8         1.105077e+06  3300000  340000
9         8.939998e+05  1400000  450000
10        8.193333e+05  1148000  650000
11        5.200000e+05   520000  520000
33        6.400000e+05   640000  640000

## Consultas

In [ ]:
data["price"]>data["price"].mean()

0        False
1        False
2        False
3         True
4        False
         ...  
21608    False
21609    False
21610    False
21611    False
21612    False
Name: price, Length: 21613, dtype: bool

In [ ]:
data[data["price"]>data["price"].mean()]

id       date    price  bedrooms  bathrooms  sqft_living  \
3      2487200875 2014-12-09   604000         4       3.00         1960   
5      7237550310 2014-05-12  1225000         4       4.50         5420   
10     1736800520 2015-04-03   662500         3       2.50         3560   
15     9297300055 2015-01-24   650000         4       3.00         2950   
21     2524049179 2014-08-26  2000000         3       2.75         3050   
...           ...        ...      ...       ...        ...          ...   
21598  8956200760 2014-10-13   541800         4       2.50         3118   
21599  7202300110 2014-09-15   810000         4       3.00         3990   
21600   249000205 2014-10-15  1537000         5       3.75         4470   
21605  3448900210 2014-10-14   610685         4       2.50         2520   
21606  7936000429 2015-03-26  1007500         4       3.50         3510   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
3          5000     1.0           0     0  ...      7        1050   
5        101930     1.0           0     0  ...     11        3890   
10         9796     1.0           0     0  ...      8        1860   
15         5000     2.0           0     3  ...      9        1980   
21        44867     1.0           0     4  ...      9        2330   
...         ...     ...         ...   ...  ...    ...         ...   
21598      7866     2.0           0     2  ...      9        3118   
21599      7838     2.0           0     0  ...      9        3990   
21600      8088     2.0           0     0  ...     11        4470   
21605      6023     2.0           0     0  ...      9        2520   
21606      7200     2.0           0     0  ...      9        2600   

       sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
3                910      1965             0    98136  47.5208 -122.393   
5               1530      2001             0    98053  47.6561 -122.005   
10              1700      1965             0    98007  47.6007 -122.145   
15               970      1979             0    98126  47.5714 -122.375   
21               720      1968             0    98040  47.5316 -122.233   
...              ...       ...           ...      ...      ...      ...   
21598              0      2014             0    98001  47.2931 -122.264   
21599              0      2003             0    98053  47.6857 -122.046   
21600              0      2008             0    98004  47.6321 -122.200   
21605              0      2014             0    98056  47.5137 -122.167   
21606            910      2009             0    98136  47.5537 -122.398   

       sqft_living15  sqft_lot15  
3               1360        5000  
5               4760      101930  
10              2210        8925  
15              2140        4000  
21              4110       20336  
...              ...         ...  
21598           2673        6500  
21599           3370        6814  
21600           2780        8964  
21605           2520        6023  
21606           2050        6200  

[7919 rows x 21 columns]

In [ ]:
data["price"][data["price"]>data["price"].mean()]

3         604000
5        1225000
10        662500
15        650000
21       2000000
          ...   
21598     541800
21599     810000
21600    1537000
21605     610685
21606    1007500
Name: price, Length: 7919, dtype: int64

In [ ]:
data[(data["price"] > data["price"].mean()) & (data["price"] > 2000000)]

id       date    price  bedrooms  bathrooms  sqft_living  \
153    7855801670 2015-04-01  2250000         4       3.25         5180   
246    2025069065 2014-09-29  2400000         4       2.50         3650   
269    7960900060 2015-05-04  2900000         4       3.25         5050   
282    7424700045 2015-05-13  2050000         5       3.00         3830   
300    3225069065 2014-06-24  3075000         4       5.00         4550   
...           ...        ...      ...       ...        ...          ...   
21310  2154970020 2014-07-03  2351956         4       4.25         5010   
21368  9533100285 2014-06-30  2065000         4       3.75         4350   
21506  2524069097 2014-05-09  2238888         5       6.50         7270   
21530  8964800330 2015-04-07  3000000         4       3.75         5090   
21576  9253900271 2015-01-07  3567000         5       4.50         4850   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
153       19850     2.0           0     3  ...     12        3540   
246        8354     1.0           1     4  ...      9        1830   
269       20100     1.5           0     2  ...     11        4750   
282        8480     2.0           0     1  ...      9        2630   
300       18641     1.0           1     4  ...     10        2600   
...         ...     ...         ...   ...  ...    ...         ...   
21310     19412     2.0           0     1  ...     11        4000   
21368      7965     2.0           0     0  ...     10        4350   
21506    130017     2.0           0     0  ...     12        6420   
21530     14823     1.0           0     0  ...     11        4180   
21576     10584     2.0           1     4  ...     10        3540   

       sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
153             1640      2006             0    98006  47.5620 -122.162   
246             1820      2000             0    98074  47.6338 -122.072   
269              300      1982          2008    98004  47.6312 -122.223   
282             1200      1905          1994    98122  47.6166 -122.287   
300             1950      2002             0    98074  47.6053 -122.077   
...              ...       ...           ...      ...      ...      ...   
21310           1010      2014             0    98040  47.5455 -122.211   
21368              0      2013             0    98004  47.6289 -122.205   
21506            850      2010             0    98027  47.5371 -121.982   
21530            910      2013             0    98004  47.6200 -122.207   
21576           1310      2007             0    98008  47.5943 -122.110   

       sqft_living15  sqft_lot15  
153             3160        9750  
246             3120       18841  
269             3890       20060  
282             3050        7556  
300             4550       19508  
...              ...         ...  
21310           3820       17064  
21368           2190        8557  
21506           1800       44890  
21530           3030       12752  
21576           3470       18270  

[198 rows x 21 columns]

In [ ]:
data[(data["price"] < 3000000) & (data["price"] > 2000000)]

id       date    price  bedrooms  bathrooms  sqft_living  \
153    7855801670 2015-04-01  2250000         4       3.25         5180   
246    2025069065 2014-09-29  2400000         4       2.50         3650   
269    7960900060 2015-05-04  2900000         4       3.25         5050   
282    7424700045 2015-05-13  2050000         5       3.00         3830   
312    1860600135 2014-05-02  2384000         5       2.50         3650   
...           ...        ...      ...       ...        ...          ...   
21040  6447300365 2014-11-13  2900000         5       4.00         5190   
21201   518500460 2014-10-08  2230000         3       3.50         3760   
21310  2154970020 2014-07-03  2351956         4       4.25         5010   
21368  9533100285 2014-06-30  2065000         4       3.75         4350   
21506  2524069097 2014-05-09  2238888         5       6.50         7270   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
153       19850     2.0           0     3  ...     12        3540   
246        8354     1.0           1     4  ...      9        1830   
269       20100     1.5           0     2  ...     11        4750   
282        8480     2.0           0     1  ...      9        2630   
312        9050     2.0           0     4  ...     10        3370   
...         ...     ...         ...   ...  ...    ...         ...   
21040     14600     2.0           0     1  ...     11        5190   
21201      5634     2.0           1     4  ...     11        2830   
21310     19412     2.0           0     1  ...     11        4000   
21368      7965     2.0           0     0  ...     10        4350   
21506    130017     2.0           0     0  ...     12        6420   

       sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
153             1640      2006             0    98006  47.5620 -122.162   
246             1820      2000             0    98074  47.6338 -122.072   
269              300      1982          2008    98004  47.6312 -122.223   
282             1200      1905          1994    98122  47.6166 -122.287   
312              280      1921             0    98119  47.6345 -122.367   
...              ...       ...           ...      ...      ...      ...   
21040              0      2013             0    98039  47.6102 -122.225   
21201            930      2014             0    98056  47.5285 -122.205   
21310           1010      2014             0    98040  47.5455 -122.211   
21368              0      2013             0    98004  47.6289 -122.205   
21506            850      2010             0    98027  47.5371 -121.982   

       sqft_living15  sqft_lot15  
153             3160        9750  
246             3120       18841  
269             3890       20060  
282             3050        7556  
312             2880        5400  
...              ...         ...  
21040           3840       19250  
21201           3560        5762  
21310           3820       17064  
21368           2190        8557  
21506           1800       44890  

[148 rows x 21 columns]

In [ ]:
data_filtrada = data[(data["price"] < 3000000) & (data["price"] > 2000000)]
data_filtrada

id       date    price  bedrooms  bathrooms  sqft_living  \
153    7855801670 2015-04-01  2250000         4       3.25         5180   
246    2025069065 2014-09-29  2400000         4       2.50         3650   
269    7960900060 2015-05-04  2900000         4       3.25         5050   
282    7424700045 2015-05-13  2050000         5       3.00         3830   
312    1860600135 2014-05-02  2384000         5       2.50         3650   
...           ...        ...      ...       ...        ...          ...   
21040  6447300365 2014-11-13  2900000         5       4.00         5190   
21201   518500460 2014-10-08  2230000         3       3.50         3760   
21310  2154970020 2014-07-03  2351956         4       4.25         5010   
21368  9533100285 2014-06-30  2065000         4       3.75         4350   
21506  2524069097 2014-05-09  2238888         5       6.50         7270   

       sqft_lot  floors  waterfront  view  ...  grade  sqft_above  \
153       19850     2.0           0     3  ...     12        3540   
246        8354     1.0           1     4  ...      9        1830   
269       20100     1.5           0     2  ...     11        4750   
282        8480     2.0           0     1  ...      9        2630   
312        9050     2.0           0     4  ...     10        3370   
...         ...     ...         ...   ...  ...    ...         ...   
21040     14600     2.0           0     1  ...     11        5190   
21201      5634     2.0           1     4  ...     11        2830   
21310     19412     2.0           0     1  ...     11        4000   
21368      7965     2.0           0     0  ...     10        4350   
21506    130017     2.0           0     0  ...     12        6420   

       sqft_basement  yr_built  yr_renovated  zipcode      lat     long  \
153             1640      2006             0    98006  47.5620 -122.162   
246             1820      2000             0    98074  47.6338 -122.072   
269              300      1982          2008    98004  47.6312 -122.223   
282             1200      1905          1994    98122  47.6166 -122.287   
312              280      1921             0    98119  47.6345 -122.367   
...              ...       ...           ...      ...      ...      ...   
21040              0      2013             0    98039  47.6102 -122.225   
21201            930      2014             0    98056  47.5285 -122.205   
21310           1010      2014             0    98040  47.5455 -122.211   
21368              0      2013             0    98004  47.6289 -122.205   
21506            850      2010             0    98027  47.5371 -121.982   

       sqft_living15  sqft_lot15  
153             3160        9750  
246             3120       18841  
269             3890       20060  
282             3050        7556  
312             2880        5400  
...              ...         ...  
21040           3840       19250  
21201           3560        5762  
21310           3820       17064  
21368           2190        8557  
21506           1800       44890  

[148 rows x 21 columns]

In [ ]:
data_filtrada.index

Int64Index([  153,   246,   269,   282,   312,   518,   540,   779,   814,
             1031,
            ...
            20326, 20441, 20535, 20664, 20767, 21040, 21201, 21310, 21368,
            21506],
           dtype='int64', length=148)

In [ ]:
data_filtrada.loc[153]

id                        7855801670
date             2015-04-01 00:00:00
price                        2250000
bedrooms                           4
bathrooms                       3.25
sqft_living                     5180
sqft_lot                       19850
floors                           2.0
waterfront                         0
view                               3
condition                          3
grade                             12
sqft_above                      3540
sqft_basement                   1640
yr_built                        2006
yr_renovated                       0
zipcode                        98006
lat                           47.562
long                        -122.162
sqft_living15                   3160
sqft_lot15                      9750
Name: 153, dtype: object

In [ ]:
data_filtrada.reset_index(drop=True, inplace=True)

In [ ]:
data_filtrada.index

RangeIndex(start=0, stop=148, step=1)

In [ ]:
data_filtrada["date"].unique()

array(['2015-04-01T00:00:00.000000000', '2014-09-29T00:00:00.000000000',
       '2015-05-04T00:00:00.000000000', '2015-05-13T00:00:00.000000000',
       '2014-05-02T00:00:00.000000000', '2014-11-14T00:00:00.000000000',
       '2015-02-18T00:00:00.000000000', '2014-06-12T00:00:00.000000000',
       '2015-03-25T00:00:00.000000000', '2015-04-17T00:00:00.000000000',
       '2014-06-25T00:00:00.000000000', '2015-02-09T00:00:00.000000000',
       '2015-05-11T00:00:00.000000000', '2015-03-30T00:00:00.000000000',
       '2014-10-29T00:00:00.000000000', '2014-09-03T00:00:00.000000000',
       '2014-11-19T00:00:00.000000000', '2015-01-12T00:00:00.000000000',
       '2014-08-29T00:00:00.000000000', '2014-07-02T00:00:00.000000000',
       '2014-06-23T00:00:00.000000000', '2014-11-24T00:00:00.000000000',
       '2014-05-19T00:00:00.000000000', '2014-05-29T00:00:00.000000000',
       '2014-05-13T00:00:00.000000000', '2014-12-19T00:00:00.000000000',
       '2014-12-03T00:00:00.000000000', '2014-09-18

In [ ]:
data_filtrada.drop("date",axis=1,inplace=True)

<ipython-input-97-0d0787906690>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_filtrada.drop("date",axis=1,inplace=True)


In [ ]:
data_filtrada.columns

Index(['id', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode', 'lat', 'long',
       'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [ ]:
new_dataset = data[['id', 'price', 'bedrooms']]
new_dataset

id   price  bedrooms
0      7129300520  221900         3
1      6414100192  538000         3
2      5631500400  180000         2
3      2487200875  604000         4
4      1954400510  510000         3
...           ...     ...       ...
21608   263000018  360000         3
21609  6600060120  400000         4
21610  1523300141  402101         2
21611   291310100  400000         3
21612  1523300157  325000         2

[21613 rows x 3 columns]

from matplotlib import pyplot as plt
new_dataset['id'].plot(kind='hist', bins=20, title='id')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
new_dataset['price'].plot(kind='hist', bins=20, title='price')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
new_dataset['bedrooms'].plot(kind='hist', bins=20, title='bedrooms')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
new_dataset.plot(kind='scatter', x='id', y='price', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
new_dataset.plot(kind='scatter', x='price', y='bedrooms', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
new_dataset['id'].plot(kind='line', figsize=(8, 4), title='id')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
new_dataset['price'].plot(kind='line', figsize=(8, 4), title='price')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
new_dataset['bedrooms'].plot(kind='line', figsize=(8, 4), title='bedrooms')
plt.gca().spines[['top', 'right']].set_visible(False)

In [ ]:
new_dataset["price"].iloc[10:200] = None

<ipython-input-100-11e3e5028891>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_dataset["price"].iloc[10:200] = None


In [ ]:
new_dataset["price"].iloc[10:200]

10    NaN
11    NaN
12    NaN
13    NaN
14    NaN
       ..
195   NaN
196   NaN
197   NaN
198   NaN
199   NaN
Name: price, Length: 190, dtype: float64

In [ ]:
new_dataset.isna().sum()

id            0
price       190
bedrooms      0
dtype: int64

In [ ]:
new_dataset.fillna(0).isna().sum()

id          0
price       0
bedrooms    0
dtype: int64

In [ ]:
new_dataset.dropna(inplace=True)


<ipython-input-108-470e5ca84cd0>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_dataset.dropna(inplace=True)


In [ ]:
new_dataset.isna().sum()

id          0
price       0
bedrooms    0
dtype: int64

**Revisar:** loc y iloc

## Objetos

In [ ]:
class Person:
    department = 'School of Information' #a class variable

    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):
        self.location = new_location

In [ ]:
person = Person()
person.set_name('Christopher Brooks')
person.set_location('Ann Arbor, MI, USA')
print('{} live in {} and works in the department {}'.format(person.name, person.location, person.department))

Christopher Brooks live in Ann Arbor, MI, USA and works in the department School of Information


## Arrays in Python

In [ ]:
import numpy as np

In [ ]:
mylist = [1, 2, 3]
x = np.array(mylist)
x

array([1, 2, 3])

In [ ]:
y = np.array([4, 5, 6])
y

array([4, 5, 6])

In [ ]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [ ]:
m.shape

(2, 3)

In [ ]:
n = np.arange(0, 30, 2) # start at 0 count up by 2, stop before 30
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [ ]:
n = n.reshape(3, 5) # reshape array to be 3x5
n

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [ ]:
o = np.linspace(0, 4, 9) # return 9 evenly spaced values from 0 to 4
o

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. ])

In [ ]:
o.resize(3, 3)
o

array([[0. , 0.5, 1. ],
       [1.5, 2. , 2.5],
       [3. , 3.5, 4. ]])

In [ ]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])